server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://47.114.106.209:3306/aiwo_meiye?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: jbs-api-test-mysql

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: top.hapleow.hapcodeweb.model.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

