server:
  port: 9000

spring:
  datasource:
    url: jdbc:sqlserver://10.17.6.127:2433;DatabaseName=lzcs
    username: lzmsuser
    password: Udfoiu*$jlasdf723@sldkx7234kdAQIdkx

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: top.hapleow.hapcodeweb.model.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
